import type { NextPage } from 'next';
import Head from 'next/head';
import Main from '../components/Main';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>모투 | 모두의 투자</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Main />

      <footer>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by ckyeon and naamukim
        </a>
      </footer>
    </div>
  );
};

export default Home;
